#!/usr/bin/env bash

# 批量重命名文件夹脚本
# 将当前目录下的英文文件夹重命名为对应的中文名
# 使用前请备份或在无误后再执行

# 英文文件夹名列表
engs=(
  "API Key Leaks"
  "Account Takeover"
  "Business Logic Errors"
  "CORS Misconfiguration"
  "CRLF Injection"
  "CSV Injection"
  "CVE Exploits"
  "Clickjacking"
  "Client Side Path Traversal"
  "Command Injection"
  "Cross-Site Request Forgery"
  "Cross Site Request Forgery"
  "DNS Rebinding"
  "DOM Clobbering"
  "Denial of Service"
  "Dependency Confusion"
  "Directory Traversal"
  "External Variable Modification"
  "File Inclusion"
  "Google Web Toolkit"
  "GraphQL Injection"
  "HTTP Parameter Pollution"
  "Headless Browser"
  "Hidden Parameters"
  "Insecure Deserialization"
  "Insecure Direct Object References"
  "Insecure Management Interface"
  "Insecure Randomness"
  "Insecure Source Code Management"
  "JSON Web Token"
  "Java RMI"
  "LDAP Injection"
  "LaTeX Injection"
  "Mass Assignment"
  "Methodology and Resources"
  "NoSQL Injection"
  "OAuth Misconfiguration"
  "ORM Leak"
  "Open Redirect"
  "Prompt Injection"
  "Prototype Pollution"
  "Race Condition"
  "Regular Expression"
  "Request Smuggling"
  "SAML Injection"
  "SQL Injection"
  "Server Side Include Injection"
  "Server Side Request Forgery"
  "Server Side Template Injection"
  "Tabnabbing"
  "Type Juggling"
  "Upload Insecure Files"
  "Web Cache Deception"
  "Web Sockets"
  "XPATH Injection"
  "XSLT Injection"
  "XSS Injection"
  "XXE Injection"
  "Zip Slip"
)

# 对应的中文文件夹名列表
cns=(
  "API 密钥和令牌泄露"
  "帐户接管"
  "业务逻辑错误"
  "跨域资源共享（CORS）配置错误"
  "回车换行符注入"
  "CSV 注入"
  "常见漏洞与暴露"
  "点击劫持 (Clickjacking)"
  "客户端路径遍历"
  "命令注入"
  "跨站请求伪造"
  "跨站请求伪造"
  "DNS 重绑定"
  "DOM 替换"
  "拒绝服务"
  "依赖混淆"
  "目录遍历"
  "外部变量修改"
  "文件包含"
  "Google Web 工具包"
  "GraphQL 注入"
  "HTTP 参数污染"
  "无头浏览器"
  "HTTP 隐藏参数"
  "不安全的反序列化"
  "不安全的直接对象引用"
  "不安全的管理接口"
  "不安全的随机性"
  "不安全的源代码管理"
  "JSON Web 令牌"
  "Java 远程方法调用"
  "LDAP 注入"
  "LaTeX 注入"
  "批量分配"
  "方法与资源"
  "NoSQL 注入"
  "OAuth 配置错误"
  "ORM 泄露"
  "开放重定向漏洞"
  "提示注入"
  "原型污染"
  "竞态条件"
  "正则表达式"
  "请求走私"
  "SAML 注入"
  "SQL 注入"
  "服务器端包含注入"
  "服务端请求伪造"
  "服务器端模板注入"
  "标签诱骗"
  "类型转换"
  "文件不安全上传"
  "网页缓存欺骗"
  "网络套接字"
  "XPath 注入"
  "XSLT 注入"
  "跨站脚本攻击（XSS）"
  "XML 外部实体"
  "Zip Slip 漏洞"
)

# 检查数组长度
if [ "${#engs[@]}" -ne "${#cns[@]}" ]; then
  echo "错误：英文字段和中文字段数量不一致！"
  exit 1
fi

# 执行重命名
for i in "${!engs[@]}"; do
  src="${engs[$i]}"
  dst="${cns[$i]}"
  if [ -d "$src" ]; then
    echo "正在重命名：'$src' -> '$dst'"
    mv -- "$src" "$dst"
  else
    echo "跳过：未找到目录 '$src'"
  fi
done

echo "批量重命名完成！"
